# Generated by Django 5.0.1 on 2024-02-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('email', models.EmailField(max_length=277, verbose_name='Author Email')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('edition', models.CharField(max_length=50, verbose_name='Edition')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.author', verbose_name='Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
