# Generated by Django 5.0.1 on 2024-02-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_author_book_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
