# Generated by Django 5.0.1 on 2024-02-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_remove_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=277, null=True, verbose_name='Author Email'),
        ),
    ]
